    resource_group_name = "rg-IaCAutomation-CB-USE2-D-PRI" 
    location = "eastus2" 
    rg_tags = {
    "CCoE_ID_Number":  "23-0304",
    "Application_Name":  "IaCAutomation",
    "CCoE_Cloud_Planning_Manager":  "Mario Alberto GonzÃ¡lez Vallejo",
    "CCoE_Architect":  "Balwant Singh",
    "Business_Project_Manager":  "Leo Rajapakse \u003cleo.rajapakse@grupobimbo.com\u003e",
    "Application_Owner":  "alberto.gonzalez06@grupobimbo.com",
    "Application_Technical_Contact":  "balwant.singh@gbsupport.net",
    "Distribution_List":  "CCOEArchitecture@gbconnect.onmicrosoft.com",
    "Entity_Name":  "Corporativo Bimbo",
    "DR_HA":  "N/A"
}
Function_app_tags = {
    "CCoE_ID_Number":  "23-0304",
    "Application_Name":  "IaCAutomation",
    "Entity":  "CB",
    "Organization":  "CORP",
    "CHG_Ticket":  "CHG0052951",
    "Resource_Groups":  "rg-IaCAutomation-CB-USE2-D-PRI",
    "Launch_Date":  "15/05/2025",
    "Resource_Description":  "IaC_Automation_200"
}

FunctionApp = {
    "FunctionApp_1":  {
                          "Hosting_plan":  "Consumption",
                          "Pricing_Plan":  "Elastic Premium EP2 250.08 USD/Month (Estimated) ACU: 420, Memory: 7 GB, vCPU: 2",
                          "AZ_Region":  "East US 2",
                          "Function_App_Plan_Name":  "CBTAUTOASPCD01",
                          "Resource_Description":  "IaC_Automation_200",
                          "Operating_System":  "Windows",
                          "Web_App_Name":  "CBTAUTOFCNCD01",
                          "Publish":  "",
                          "Runtime_Stack":  "java_version",
                          "Runtime_Stack_verison":  "17",
                          "tomcatVersion":  "10.0",
                          "Linux_Plan":  "",
                          "Windows_Plan":  "testing",
                          "Zone_redundancy":  "",
                          "Enable_Application_Insights":  "No",
                          "vnetname":  null,
                          "vnet_rg":  null,
                          "Storage_Account_Name":  "testing",
                          "Diagnostic_Settings":  "Don\u0027t Configure",
                          "Workspace":  "",
                          "Enable_public_access":  "off",
                          "Enable_network_injection":  "",
                          "Enable_private_endpoints":  "",
                          "Inbound_subnet":  "",
                          "Enable_Vnet_Integration":  "",
                          "Outbound_subnet":  "",
                          "Basic_Authentication":  "Enable",
                          "Azure_Container_Apps_Environment":  "testing",
                          "Use_quickstart_image":  "",
                          "Image_type":  "",
                          "Image_Name":  "",
                          "Image_registry_login_server":  "",
                          "Image_registry_user_name":  "",
                          "Image_registry_password":  "",
                          "Workload_profile":  "",
                          "CPU_and_memory":  ""
                      },
    "FunctionApp_2":  {
                          "Hosting_plan":  "Functions Premium",
                          "Pricing_Plan":  "Elastic Premium EP2 250.08 USD/Month (Estimated) ACU: 420, Memory: 7 GB, vCPU: 2",
                          "AZ_Region":  "East US 2",
                          "Function_App_Plan_Name":  "CBTAUTOASPCD02",
                          "Resource_Description":  "IaC_Automation_200",
                          "Operating_System":  "Linux",
                          "Web_App_Name":  "CBTAUTOFCNCD02",
                          "Publish":  "Code",
                          "Runtime_Stack":  "java_version",
                          "Runtime_Stack_verison":  "17",
                          "tomcatVersion":  "10.0",
                          "Linux_Plan":  "testing",
                          "Windows_Plan":  "",
                          "Zone_redundancy":  "",
                          "Enable_Application_Insights":  "Yes",
                          "vnetname":  "vn-dev-eus2",
                          "vnet_rg":  "rgp-allDev-Dev-eus2",
                          "Storage_Account_Name":  "testing",
                          "Diagnostic_Settings":  "Configure",
                          "Workspace":  "testing",
                          "Enable_public_access":  "on",
                          "Enable_network_injection":  "on",
                          "Enable_private_endpoints":  "on",
                          "Inbound_subnet":  "testing",
                          "Enable_Vnet_Integration":  "testing",
                          "Outbound_subnet":  "testing",
                          "Basic_Authentication":  "Disable",
                          "Azure_Container_Apps_Environment":  "testing",
                          "Use_quickstart_image":  "",
                          "Image_type":  "",
                          "Image_Name":  "",
                          "Image_registry_login_server":  "",
                          "Image_registry_user_name":  "",
                          "Image_registry_password":  "",
                          "Workload_profile":  "",
                          "CPU_and_memory":  ""
                      },
    "FunctionApp_3":  {
                          "Hosting_plan":  "App Service",
                          "Pricing_Plan":  "Elastic Premium EP2 250.08 USD/Month (Estimated) ACU: 420, Memory: 7 GB, vCPU: 2",
                          "AZ_Region":  "East US 2",
                          "Function_App_Plan_Name":  "CBTAUTOASPCD03",
                          "Resource_Description":  "IaC_Automation_200",
                          "Operating_System":  "Linux",
                          "Web_App_Name":  "CBTAUTOFCNCD03",
                          "Publish":  "Code",
                          "Runtime_Stack":  "java_version",
                          "Runtime_Stack_verison":  "17",
                          "tomcatVersion":  "10.0",
                          "Linux_Plan":  "testing",
                          "Windows_Plan":  "",
                          "Zone_redundancy":  "",
                          "Enable_Application_Insights":  "Yes",
                          "vnetname":  "vn-dev-eus2",
                          "vnet_rg":  "rgp-allDev-Dev-eus2",
                          "Storage_Account_Name":  "testing",
                          "Diagnostic_Settings":  "Configure",
                          "Workspace":  "testing",
                          "Enable_public_access":  "on",
                          "Enable_network_injection":  "on",
                          "Enable_private_endpoints":  "off",
                          "Inbound_subnet":  "",
                          "Enable_Vnet_Integration":  "testing",
                          "Outbound_subnet":  "testing",
                          "Basic_Authentication":  "Disable",
                          "Azure_Container_Apps_Environment":  "testing",
                          "Use_quickstart_image":  "",
                          "Image_type":  "",
                          "Image_Name":  "",
                          "Image_registry_login_server":  "",
                          "Image_registry_user_name":  "",
                          "Image_registry_password":  "",
                          "Workload_profile":  "",
                          "CPU_and_memory":  ""
                      },
    "FunctionApp_4":  {
                          "Hosting_plan":  "Container Apps environment",
                          "Pricing_Plan":  "",
                          "AZ_Region":  "East US 2",
                          "Function_App_Plan_Name":  "CBTAUTOASPCD04",
                          "Resource_Description":  "IaC_Automation_200",
                          "Operating_System":  "",
                          "Web_App_Name":  "CBTAUTOFCNCD04",
                          "Publish":  "",
                          "Runtime_Stack":  "",
                          "Runtime_Stack_verison":  "",
                          "tomcatVersion":  null,
                          "Linux_Plan":  "",
                          "Windows_Plan":  "",
                          "Zone_redundancy":  "",
                          "Enable_Application_Insights":  "Yes",
                          "vnetname":  null,
                          "vnet_rg":  null,
                          "Storage_Account_Name":  "testing",
                          "Diagnostic_Settings":  "Configure",
                          "Workspace":  "testing",
                          "Enable_public_access":  "",
                          "Enable_network_injection":  "",
                          "Enable_private_endpoints":  "",
                          "Inbound_subnet":  "",
                          "Enable_Vnet_Integration":  "",
                          "Outbound_subnet":  "",
                          "Basic_Authentication":  "",
                          "Azure_Container_Apps_Environment":  "",
                          "Use_quickstart_image":  "no",
                          "Image_type":  "testing",
                          "Image_Name":  "",
                          "Image_registry_login_server":  "testing",
                          "Image_registry_user_name":  "testing",
                          "Image_registry_password":  "testing",
                          "Workload_profile":  "testing",
                          "CPU_and_memory":  "2 CPU cores, 4 Gi memory"
                      }
}
